In [ ]:
import cv2
import numpy as np
import os

# Data preparation
dataset_path = "./data/"
faceData = []
labels = []
nameMap = {}
offset = 20

classId = 0

for f in os.listdir(dataset_path):
    if f.endswith(".npy"):
        nameMap[classId] = f[:-4]
        # x-value
        dataItem = np.load(dataset_path + f)
        m = dataItem.shape[0]
        faceData.append(dataItem)
        
        # y-values
        target = classId * np.ones((m,))
        classId += 1
        labels.append(target)

XT = np.concatenate(faceData, axis=0)
yT = np.concatenate(labels, axis=0).reshape((-1, 1))

print(XT.shape)
print(yT.shape)
print(nameMap)

# Algorithm
def dist(p, q):
    return np.sqrt(np.sum((p - q) ** 2))

def knn(X, y, xt, k=5):
    m = X.shape[0]
    dlist = []
    
    for i in range(m):
        d = dist(X[i], xt)
        dlist.append((d, y[i]))
    
    dlist = sorted(dlist, key=lambda x: x[0])
    dlist = np.array(dlist[:k], dtype=object)
    labels = dlist[:, 1]
    
    labels, cnts = np.unique(labels, return_counts=True)
    idx = cnts.argmax()
    pred = labels[idx]
    
    return int(pred.item())  # Convert single-element array to an integer

# Predictions
# Create camera object
cam = cv2.VideoCapture(0)
model = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")

while True:
    success, img = cam.read()
    if not success:
        print("Reading Camera Failed!")
        break
    
    faces = model.detectMultiScale(img, 1.3, 5)
  
    # Render a box around each face and predict its name
    for f in faces:
        x, y, w, h = f
        print(f)
        
        # Ensure the crop coordinates are within image bounds
        if y - offset < 0 or y + h + offset > img.shape[0] or x - offset < 0 or x + w + offset > img.shape[1]:
            continue

        # Crop and save the largest face
        cropped_face = img[y - offset:y + h + offset, x - offset:x + w + offset]

        # Check if cropped_face is not empty
        if cropped_face.size == 0:
            continue

        cropped_face = cv2.resize(cropped_face, (100, 100))

        # Predict the name using KNN
        classPredicted = knn(XT, yT, cropped_face.flatten())
        # Name
        namePredicted = nameMap[classPredicted]
        print(namePredicted)
        # Display the Name and Box
        
        cv2.putText(img, namePredicted, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 200, 0), 2, cv2.LINE_AA)
        cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)
        
    cv2.imshow("Prediction Window", img)
    
    key = cv2.waitKey(1)  # Pause here for 1 ms before you read the next image
    if key == ord('q'):
        break

# Release Camera, and Destroy Window
cam.release()
cv2.destroyAllWindows()


(278, 30000)
(278, 1)
{0: 'Harjeet', 1: 'Anishu', 2: 'Supreet', 3: 'nitul', 4: 'Simran'}
[785 445  56  56]
nitul
[786 447  55  55]
nitul
[787 447  56  56]
nitul
[787 447  55  55]
nitul
[787 446  54  54]
nitul
[786 446  55  55]
nitul
[787 448  54  54]
nitul
[789 448  54  54]
nitul
[791 449  53  53]
nitul
[791 449  55  55]
nitul
[791 450  53  53]
nitul
[793 450  54  54]
nitul
[799 453  49  49]
nitul
[799 452  56  56]
nitul
[800 452  54  54]
nitul
[797 446  53  53]
nitul
[796 441  55  55]
nitul
[798 443  55  55]
nitul
[803 448  55  55]
nitul
[806 449  54  54]
nitul
[806 447  56  56]
nitul
[807 448  55  55]
nitul
[810 449  55  55]
nitul
[816 451  55  55]
nitul
[821 454  55  55]
nitul
[826 457  54  54]
nitul
[829 458  55  55]
nitul
[830 458  54  54]
nitul
[829 457  54  54]
nitul
[830 459  53  53]
nitul
[831 459  55  55]
nitul
[831 459  56  56]
nitul
[830 458  55  55]
nitul
[830 457  55  55]
nitul
[830 459  53  53]
nitul
[829 459  56  56]
nitul
[829 460  55  55]
nitul
[830 460  54  54]
nitul

[813 336  58  58]
nitul
[843 337  58  58]
nitul
[876 343  59  59]
nitul
[896 347  57  57]
nitul
[899 347  56  56]
nitul
[900 344  57  57]
nitul
[898 345  57  57]
nitul
[897 346  57  57]
nitul
[891 343  58  58]
nitul
[888 342  55  55]
nitul
[886 341  56  56]
nitul
[880 340  56  56]
nitul
[869 339  56  56]
nitul
[859 336  58  58]
nitul
[859 339  54  54]
nitul
[860 339  55  55]
nitul
[864 340  54  54]
nitul
[865 337  56  56]
nitul
[866 336  55  55]
nitul
[866 337  56  56]
nitul
[866 337  57  57]
nitul
[866 337  56  56]
nitul
[866 337  56  56]
nitul
[866 337  56  56]
nitul
[867 338  56  56]
nitul
[868 338  55  55]
nitul
[867 336  56  56]
nitul
[868 337  55  55]
nitul
[867 337  56  56]
nitul
[867 336  56  56]
nitul
[868 336  57  57]
nitul
[868 336  57  57]
nitul
[873 336  56  56]
nitul
[879 336  56  56]
nitul
[872 337  58  58]
nitul
[852 335  57  57]
nitul
[809 332  55  55]
nitul
[810 334  54  54]
nitul
[813 335  54  54]
nitul
[829 336  53  53]
nitul
[855 335  61  61]
nitul
[885 342  59  59

nitul
[941 234  56  56]
nitul
[936 236  58  58]
nitul
[926 239  57  57]
nitul
[914 241  58  58]
nitul
[899 245  55  55]
nitul
[879 248  56  56]
nitul
[859 248  57  57]
nitul
[838 241  59  59]
nitul
[822 231  59  59]
nitul
[812 223  59  59]
nitul
[808 221  57  57]
nitul
[809 222  56  56]
nitul
[811 226  59  59]
nitul
[820 230  57  57]
nitul
[827 229  63  63]
nitul
[834 228  59  59]
nitul
[836 226  57  57]
nitul
[838 225  58  58]
nitul
[839 229  59  59]
nitul
[841 232  58  58]
nitul
[842 229  58  58]
nitul
[841 229  58  58]
nitul
[841 228  59  59]
nitul
[840 229  57  57]
nitul
[836 229  59  59]
nitul
[832 232  60  60]
nitul
[830 235  56  56]
nitul
[826 234  61  61]
nitul
[827 235  60  60]
nitul
[829 239  57  57]
nitul
[827 240  59  59]
nitul
[827 242  58  58]
nitul
[825 243  58  58]
nitul
[821 244  61  61]
nitul
[818 248  62  62]
nitul
[817 254  61  61]
nitul
[820 258  63  63]
nitul
[823 257  64  64]
nitul
[825 259  65  65]
nitul
[820 261  62  62]
nitul
[807 261  62  62]
nitul
[796 262  

[100 102 518 518]
Supreet
[127 115 489 489]
Supreet
[118 111 506 506]
Supreet
[118 102 513 513]
Supreet
[124 115 513 513]
Supreet
[118 104 518 518]
Supreet
[ 97 101 559 559]
Supreet
[129  84 559 559]
Supreet
[135  89 506 506]
Supreet
[135  86 506 506]
Supreet
[110  80 536 536]
Supreet
[130  85 497 497]
Supreet
[113  81 513 513]
Supreet
[113  82 506 506]
Supreet
[109  81 501 501]
Supreet
[118  81 513 513]
Supreet
[108  77 513 513]
Supreet
[106  76 506 506]
Supreet
[ 92  65 536 536]
Supreet
[144  97 466 466]
Supreet
[ 92  63 528 528]
Supreet
[122  57 508 508]
Supreet
[126  54 497 497]
Supreet
[152  47 486 486]
Supreet
[134  39 513 513]
Supreet
[167  49 458 458]
Supreet
[175  37 442 442]
Supreet
[153  30 486 486]
Supreet
[163  30 466 466]
Supreet
[163  30 466 466]
Supreet
[163  35 466 466]
Supreet
[142  27 489 489]
Supreet
[134  23 513 513]
nitul
[149  56 451 451]
Supreet
[140  58 466 466]
nitul
[151  60 451 451]
Supreet
[130  51 489 489]
nitul
[161  54 448 448]
Supreet
[142  47 489 489]


[404 104 394 394]
Supreet
[1141  264   62   62]
nitul
[405 107 389 389]
Supreet
[1142  266   58   58]
nitul
[405 107 389 389]
Supreet
[1142  267   56   56]
nitul
[398 105 398 398]
Supreet
[1142  267   57   57]
nitul
[405 112 389 389]
Supreet
[1141  268   58   58]
nitul
[400 108 394 394]
Supreet
[1137  267   63   63]
nitul
[424 120 358 358]
Supreet
[1137  268   61   61]
nitul
[397 107 404 404]
Supreet
[1136  267   63   63]
nitul
[413 114 372 372]
Supreet
[1138  268   61   61]
nitul
[406 110 385 385]
Supreet
[1136  268   62   62]
nitul
[403 108 390 390]
Supreet
[1138  270   59   59]
nitul
[406 105 385 385]
Supreet
[1138  268   62   62]
nitul
[401 110 394 394]
Supreet
[1139  271   58   58]
nitul
[395 104 406 406]
Supreet
[1139  272   58   58]
nitul
[1138  272   58   58]
nitul
[388 102 412 412]
Supreet
[1139  272   57   57]
nitul
[389 101 412 412]
Supreet
[1139  272   57   57]
nitul
[392  96 412 412]
Supreet
[1138  272   59   59]
nitul
[387  99 426 426]
Supreet
[1137  271   61   61]
nitul


Supreet
[830 354  64  64]
nitul
[376 105 412 412]
Supreet
[830 351  63  63]
nitul
[364 110 412 412]
Supreet
[835 347  67  67]
nitul
[358 104 426 426]
Supreet
[842 354  62  62]
nitul
[356 108 412 412]
Supreet
[841 358  61  61]
nitul
[825 352  64  64]
nitul
[343 115 398 398]
Supreet
[811 346  65  65]
nitul
[325 102 426 426]
Supreet
[805 346  62  62]
nitul
[324 111 418 418]
Supreet
[803 347  62  62]
nitul
[330 120 394 394]
Supreet
[801 344  68  68]
nitul
[303 106 420 420]
Supreet
[804 346  65  65]
nitul
[308 108 398 398]
Supreet
[806 348  64  64]
nitul
[331 103 385 385]
Supreet
[811 354  66  66]
nitul
[355  99 394 394]
Supreet
[817 362  63  63]
nitul
[365  93 394 394]
Supreet
[819 367  69  69]
nitul
[403 113 348 348]
Supreet
[830 374  69  69]
nitul
[837 379  71  71]
nitul
[412 125 335 335]
Supreet
[846 383  70  70]
nitul
[410 134 317 317]
Supreet
[838 382  70  70]
nitul
[396 143 312 312]
Supreet
[836 383  70  70]
nitul
[362 146 309 309]
Supreet
[838 390  72  72]
nitul
[846 400  74  74]
ni

[332 162 376 376]
Supreet
[1040  233  178  178]
nitul
[1010  243  179  179]
nitul
[983 248 181 181]
nitul
[324 160 373 373]
Supreet
[984 247 180 180]
nitul
[994 250 182 182]
nitul
[315 154 389 389]
Supreet
[311 149 398 398]
Supreet
[1015  250  180  180]
nitul
[306 150 404 404]
Supreet
[1038  250  175  175]
nitul
[1052  250  179  179]
nitul
[311 152 394 394]
Supreet
[1044  248  194  194]
nitul
[316 154 389 389]
Supreet
[1039  256  192  192]
nitul
[315 156 394 394]
Supreet
[1029  255  187  187]
nitul
[1013  245  189  189]
nitul
[310 161 389 389]
Supreet
[999 246 174 174]
nitul
[308 159 398 398]
Supreet
[1012  239  176  176]
nitul
[309 160 385 385]
Supreet
[1090  238  175  175]
[312 160 385 385]
Supreet
[310 157 385 385]
Supreet
[306 157 394 394]
Supreet
[306 157 394 394]
Supreet
[316 168 377 377]
Supreet
[308 148 412 412]
Supreet
[319 146 389 389]
Supreet
[337 168 362 362]
Supreet
[326 153 390 390]
Supreet
[329 146 397 397]
Supreet
[547 455 213 213]
nitul
[500 476 181 181]
nitul
[499 476

nitul
[310 235 167 167]
nitul
[312 239 163 163]
nitul
[310 237 168 168]
nitul
[314 236 161 161]
nitul
[313 232 167 167]
nitul
[318 231 166 166]
nitul
[323 235 159 159]
nitul
[324 238 159 159]
nitul
[324 238 162 162]
nitul
[327 236 160 160]
nitul
[325 235 158 158]
nitul
[323 230 162 162]
nitul
[324 227 163 163]
nitul
[330 221 164 164]
nitul
[334 219 160 160]
nitul
[332 217 163 163]
nitul
[327 220 165 165]
nitul
[326 223 162 162]
nitul
[325 218 168 168]
nitul
[333 210 163 163]
nitul
[336 198 169 169]
nitul
[342 193 162 162]
nitul
[351 179 167 167]
Simran
[363 167 164 164]
nitul
[371 161 159 159]
nitul
[365 161 170 170]
Simran
[361 173 158 158]
nitul
[345 175 175 175]
Simran
[343 180 166 166]
Supreet
[339 180 171 171]
nitul
[337 185 171 171]
nitul
[331 194 171 171]
nitul
[325 202 171 171]
nitul
[322 202 174 174]
nitul
[325 204 166 166]
nitul
[332 196 170 170]
nitul
[342 194 158 158]
nitul
[347 192 157 157]
nitul
[345 196 163 163]
nitul
[339 195 168 168]
nitul
[344 196 161 161]
nitul
[343 

[770 406 120 120]
nitul
[779 432 119 119]
nitul
[743 427 117 117]
nitul
[679 411 125 125]
nitul
[478 360  97  97]
nitul
[501 347 106 106]
nitul
[602 321 111 111]
nitul
[669 299 111 111]
nitul
[730 292 103 103]
nitul
[780 297  94  94]
nitul
[795 306  89  89]
nitul
[443 304 123 123]
nitul
[346 437 120 120]
nitul
[339 502 122 122]
Simran
[349 533 140 140]
nitul
[396 532 125 125]
Simran
[419 516 123 123]
nitul
[433 507 127 127]
nitul
[431 505 121 121]
nitul
[403 499 126 126]
nitul
[355 497 129 129]
nitul
[321 489 128 128]
nitul
[302 466 132 132]
Simran
[306 425 135 135]
nitul
[320 371 139 139]
nitul
[290   9 135 135]
[270  89 150 150]
nitul
[255 153 146 146]
nitul
[238 203 145 145]
nitul
[214 246 148 148]
nitul
[187 284 148 148]
nitul
[167 312 144 144]
nitul
[150 331 142 142]
nitul
[142 346 131 131]
nitul
[135 345 127 127]
nitul
[143 338 128 128]
nitul
[178 338 126 126]
nitul
[238 339 135 135]
nitul
[332 340 133 133]
nitul
[412 335 154 154]
nitul
[496 335 153 153]
nitul
[567 347 137 137]
n

[442  32 559 559]
Supreet
[450  40 536 536]
Supreet
[459  44 526 526]
Supreet
[462  47 513 513]
Supreet
[457  41 526 526]
Supreet
[448  37 554 554]
Supreet
[475  59 513 513]
Supreet
[466  48 536 536]
Supreet
[470  48 536 536]
Supreet
[466  48 536 536]
Supreet
[490  54 489 489]
Supreet
[477  42 546 546]
Supreet
[432  64 536 536]
Supreet
[511  54 489 489]
Supreet
[443  44 536 536]
Supreet
[491 433 152 152]
nitul
[489 430 157 157]
nitul
[487 429 157 157]
nitul
[352  29 451 451]
Supreet
[377  27 466 466]
Supreet
[361  23 466 466]
Supreet
[366  23 466 466]
Supreet
[369  19 466 466]
[379  23 466 466]
Supreet
[384  23 466 466]
Supreet
[391  41 448 448]
Supreet
[398  40 451 451]
Supreet
[392  31 466 466]
Supreet
[392  27 466 466]
Supreet
[392  27 466 466]
Supreet
